name: anime_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  cupertino_icons: ^1.0.2
  jikan_api: ^2.1.0
  url_launcher: ^6.1.14
  video_player: ^2.7.2
  chewie: ^1.7.1
  flutter_youtube_view: ^2.0.4
  youtube_player_flutter: ^8.1.2
  material_design_icons_flutter: ^7.0.7296
  cached_network_image: ^3.3.0
  just_audio: ^0.9.35
  
flutter:
  assets:
    - assets/no-image.jpg
    - assets/goku.jpg
    - assets/placeholder.png
    - assets/epicgoku.jpg
    - assets/uiTheme.mp3
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
