name: anime_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  cupertino_icons: ^1.0.2
  jikan_api: ^2.1.0
  url_launcher: ^6.1.14
  video_player: ^2.7.2
  chewie: ^1.7.1
  flutter_youtube_view: ^2.0.4
  youtube_player_flutter: ^8.1.2
  material_design_icons_flutter: ^7.0.7296
  cached_network_image: ^3.3.0
  just_audio: ^0.9.35
  translator: ^0.1.7
  firebase_auth: ^4.14.1
  provider: ^6.0.5
  flutter_secure_storage: ^9.0.0
  firebase_core: ^2.23.0
  pigeon: ^14.0.0
  cloud_firestore: ^4.13.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3

flutter:
  uses-material-design: true # Agregamos esta línea
  assets:
    - assets/no-image.jpg
    - assets/goku.jpg
    - assets/placeholder.png
    - assets/epicgoku.jpg
    - assets/play.jpg
    - assets/mute.jpg
    - assets/github.png
    - assets/gokugod.gif
    - assets/uiTheme.mp3
    #- packages/cupertino_icons/assets/CupertinoIcons.ttf # Agregamos estas líneas
    #- packages/material_design_icons_flutter/fonts/MaterialIcons-Regular.ttf
